apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/ingress-nginx
    repoURL: https://github.com/dgo19/microk8s-walkthrough.git
    targetRevision: HEAD
  syncPolicy: {}
