apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-operator
  namespace: argocd
spec:
  destination:
    namespace: postgres-operator
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/postgres-operator
    repoURL: git@gitlab.home:argocd-k8s-home/applications.git
    targetRevision: HEAD
  syncPolicy: {}
