apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-test-my-webserver
  namespace: argocd
spec:
  destination:
    namespace: test-my-webserver
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/test-my-webserver
    repoURL: https://github.com/dgo19/microk8s-walkthrough.git
    targetRevision: HEAD
  syncPolicy: {}
