apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: haproxy-ingress
  namespace: argocd
spec:
  destination:
    namespace: ingress-controller
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/haproxy-ingress
    repoURL: git@gitlab.home:argocd-k8s-home/clusterconfig.git
    targetRevision: HEAD
  syncPolicy: {}
