apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: configmaps
  namespace: argocd
spec:
  destination:
    namespace: configmaps
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/configmaps
    repoURL: https://github.com/dgo19/microk8s-walkthrough.git
    targetRevision: HEAD
  syncPolicy: {}
