apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - name: nextcloud
        image: nextcloud:19.0.0-apache
        volumeMounts:
          - name: nextcloud-persistent-storage
            mountPath: /var/www/html
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: nextcloud-config
              key: POSTGRES_HOST
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: nextcloud-config
              key: POSTGRES_DB
        - name: NEXTCLOUD_DATA_DIR
          valueFrom:
            configMapKeyRef:
              name: nextcloud-config
              key: NEXTCLOUD_DATA_DIR
        - name: NEXTCLOUD_TRUSTED_DOMAINS
          valueFrom:
            configMapKeyRef:
              name: nextcloud-config
              key: NEXTCLOUD_TRUSTED_DOMAINS
        - name: NEXTCLOUD_UPDATE
          valueFrom:
            configMapKeyRef:
              name: nextcloud-config
              key: NEXTCLOUD_UPDATE
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: nextcloud-config
              key: REDIS_HOST
        - name: REDIS_HOST_PORT
          valueFrom:
            configMapKeyRef:
              name: nextcloud-config
              key: REDIS_HOST_PORT
        - name: SMTP_HOST
          valueFrom:
            configMapKeyRef:
              name: nextcloud-config
              key: SMTP_HOST
        - name: SMTP_SECURE
          valueFrom:
            configMapKeyRef:
              name: nextcloud-config
              key: SMTP_SECURE
        - name: SMTP_PORT
          valueFrom:
            configMapKeyRef:
              name: nextcloud-config
              key: SMTP_PORT
        - name: SMTP_AUTHTYPE
          valueFrom:
            configMapKeyRef:
              name: nextcloud-config
              key: SMTP_AUTHTYPE
        - name: MAIL_FROM_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: nextcloud-config
              key: MAIL_FROM_ADDRESS
        - name: MAIL_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: nextcloud-config
              key: MAIL_DOMAIN
        - name: APACHE_DISABLE_REWRITE_IP
          valueFrom:
            configMapKeyRef:
              name: nextcloud-config
              key: APACHE_DISABLE_REWRITE_IP
        - name: TRUSTED_PROXIES
          valueFrom:
            configMapKeyRef:
              name: nextcloud-config
              key: TRUSTED_PROXIES
        - name: OVERWRITEHOST
          valueFrom:
            configMapKeyRef:
              name: nextcloud-config
              key: OVERWRITEHOST
        - name: OVERWRITEPROTOCOL
          valueFrom:
            configMapKeyRef:
              name: nextcloud-config
              key: OVERWRITEPROTOCOL
        - name: OVERWRITEWEBROOT
          valueFrom:
            configMapKeyRef:
              name: nextcloud-config
              key: OVERWRITEWEBROOT
        - name: OVERWRITECONDADDR
          valueFrom:
            configMapKeyRef:
              name: nextcloud-config
              key: OVERWRITECONDADDR
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: nextcloud.nextcloud-postgresql-cluster.credentials
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud.nextcloud-postgresql-cluster.credentials
              key: password
        - name: REDIS_HOST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: REDIS_HOST_PASSWORD
        - name: NEXTCLOUD_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: nextcloud-secret
              key: NEXTCLOUD_ADMIN_USER
        - name: NEXTCLOUD_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-secret
              key: NEXTCLOUD_ADMIN_PASSWORD
      volumes:
      - name: nextcloud-persistent-storage
        persistentVolumeClaim:
          claimName: pvc-nextcloud
