apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nextcloud

configMapGenerator:
  - name: nextcloud-config
    literals:
      - POSTGRES_HOST=nextcloud-postgresql-cluster
      - POSTGRES_DB=nextcloud
      - NEXTCLOUD_DATA_DIR=/var/www/html/data
      - NEXTCLOUD_TRUSTED_DOMAINS=
      - NEXTCLOUD_UPDATE=0
      - REDIS_HOST="redis"
      - REDIS_HOST_PORT="6379"
      - SMTP_HOST=""
      - SMTP_SECURE=""
      - SMTP_PORT=""
      - SMTP_AUTHTYPE=PLAIN
      - MAIL_FROM_ADDRESS=""
      - MAIL_DOMAIN=""
      - APACHE_DISABLE_REWRITE_IP=1
      - TRUSTED_PROXIES=""
      - OVERWRITEHOST="nextcloud.microk8s.local"
      - OVERWRITEPROTOCOL="https"
      - OVERWRITEWEBROOT=""
      - OVERWRITECONDADDR=""

secretGenerator:
  - name: redis-secret
    literals:
#      - REDIS_HOST_PASSWORD=aGai8Mei6sing8sie1soo1aedoocugh0Epha4jee8mi9soiree
      - REDIS_HOST_PASSWORD=""
  - name: nextcloud-secret
    literals:
      - NEXTCLOUD_ADMIN_USER=nextadmin
      - NEXTCLOUD_ADMIN_PASSWORD=greatpassword

resources:
  - deployment-nextcloud.yaml
  - deployment-redis.yaml
  - ingress-nextcloud.yaml
  - namespace-nextcloud.yaml
  - postgresql-cluster-nextcloud.yaml
  - pvc-nextcloud.yaml
  - service-nextcloud.yaml
  - service-redis.yaml

generatorOptions:
  disableNameSuffixHash: true
