apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: nextcloud-postgresql-cluster
spec:
  teamId: "nextcloud"
  volume:
    size: 5Gi
    storageclass: microk8s-hostpath
  numberOfInstances: 1
  users:
    nextcloud:  # database owner
    - superuser
    - createdb
  databases:
    nextcloud: nextcloud  # dbname: owner
  postgresql:
    version: "11"
