kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nextcloud
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
