apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-my-webserver
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: my-webserver.microk8s.local
    http:
      paths:
      - backend:
          serviceName: my-webserver
          servicePort: http
