apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-zabbix-web
spec:
spec:
  rules:
  - host: zabbix.microk8s.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: zabbix-web-nginx-pgsql
            port:
              number: 8080
