apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - base/

namespace: ingress-nginx

secretGenerator:
  - name: tls-secret
    namespace: ingress-nginx
    files:
      - tls.crt
      - tls.key
    type: Opaque

patches:
   - deployment-ingress-nginx-controller.yaml

generatorOptions:
  disableNameSuffixHash: true
