apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=v1.7.8

namespace: argocd

secretGenerator:
  - name: argocd-secret
    behavior: merge
#    files:
#      - tls.key
#      - tls.crt
    literals:
### create hash: htpasswd -bnBC 10 "" password | tr -d ':\n'
      - admin.password=$2y$10$KCUOEvfMR6/zTjiB4yDI0eyU3Oyul9DeDkcpKZZhW3wEHKmw1SZwa
      - admin.passwordMtime=2000-01-01T00:00:00Z
    type: Opaque
#  - name: github-key
#    files:
#      - sshPrivateKey
#    type: Opaque

#configMapGenerator:
#  - name: argocd-ssh-known-hosts-cm
#    behavior: replace
#    files:
#      - ssh_known_hosts

patchesStrategicMerge:
  - argocd-cm.yaml

resources:
  - ingress-argocd.yaml
  - namespace-argocd.yaml

images:
- name: argoproj/argocd
  digest: sha256:e3ef45ca9a6b735c23b92349a16d52a63376bb85dfd9bde6ad28b012b64605ad

generatorOptions:
  disableNameSuffixHash: true
